version: 1.0.2
slug: p1stream
name: P1Stream
description: P1 Camerastream
url: https://github.com/kurim/P1Stream
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
boot: manual
image: kur1m/p1stream
init: false
startup: system
ports:
  8554/tcp: 8554
host_network: true
homeassistant_api: true
video: true
audio: false
ingress: true
ingress_port: 1984
panel_icon: mdi:camera
map: [ "config:rw", "media", "ssl" ]
