version: 1.0.2
slug: p1stream
name: P1Stream
description: P1 Camerastream
url: https://github.com/kurim/P1Stream
arch:
  - aarch64
  - amd64
boot: manual
image: kur1m/p1stream
init: false
startup: system
ports:
  8554/tcp: 8554
host_network: true
ingress: true
ingress_port: 1984
panel_icon: mdi:camera
options:
  PRINTER_ADDRESS: null
  PRINTER_ACCESS_CODE: null
  UI_USERNAME: p1stream
  UI_PASSWORD: p1stream
  RTSP_USERNAME: p1stream
  RTSP_PASSWORD: p1stream
schema:
  PRINTER_ADDRESS: str
  PRINTER_ACCESS_CODE: password
  UI_USERNAME: str
  UI_PASSWORD: password
  RTSP_USERNAME: str
  RTSP_PASSWORD: password
